[project]
name = "california-fire-crisis"
version = "0.1.0"
description = "California Wildfire Analysis"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "jupyterlab"
]
[tool.uv]